// var deporte = {
//     conBalon["fotball, "Basketball", "Rugby],
// sinBalon ["boxeo", "Surft", "Trekking"],
//
// var persona = {nombre: "Lucas", edad: 26, estudios: {esProgramador: true}}
// console.log(persona.edad)
// persona.nombre = "martin";
// persona.edad = 32
// console.log(persona.edad);

// var autos ={}
// autos.marcas = ["Ford", "Audi", "Ferrari"];
// delete autos.marcas;
// console.log(autos);

// var misFunciones = {
//     saludar: funtion (){
//         console.log("Hola");
//     },
// };
// misFunciones.saludar();
// var atuendos = {manos: ["Guantes", "Anillos"], pies: ["Zapatos", "Soquetes"]};
// atuendos["piernas"] = ["Bermudas", "Pantalones"];
// console.log(atuendos);
// var comidas = {};
// var diferenciasDeNotationes = function (propUno, propDos){
//     comidas.[propUno] = ["Frutas", "Vegetales"]
//     comidas[propDos] = ["Hamburguesas", "PapasFritas"];
// };
// diferenciasDeNotationes("saludable", "noSaludable");
// console.log(comidas);

// var libro = {autor: "Borges", genero: "Policial", año: 1990};
// var tienePropiedad = libro.hasOwnProperty("autor");
// console.log(tienePropiedad);

// var todasLasPropiedades = Object.keys(libro);
// console.log(todasLasPropiedades);

// var mundo = {continente: 7, paises: 195, oceanos: 5};
// for(var prop in mundo){
//     console.log("Esta es la propiedad: " + prop);
//     console.log(" este es el valor: " + mundo[prop]);
// }